# Generated by Django 3.2.4 on 2021-10-04 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='title',
            field=models.CharField(default=0, max_length=300),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='news',
            name='clicks_counter',
            field=models.IntegerField(default=0),
        ),
    ]
